set(_CATKIN_CURRENT_PACKAGE "demo")
set(demo_VERSION "0.0.0")
set(demo_MAINTAINER "pi <pi@todo.todo>")
set(demo_PACKAGE_FORMAT "2")
set(demo_BUILD_DEPENDS "geometry_msgs" "rospy")
set(demo_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy")
set(demo_BUILDTOOL_DEPENDS "catkin")
set(demo_BUILDTOOL_EXPORT_DEPENDS )
set(demo_EXEC_DEPENDS "geometry_msgs" "rospy")
set(demo_RUN_DEPENDS "geometry_msgs" "rospy")
set(demo_TEST_DEPENDS )
set(demo_DOC_DEPENDS )
set(demo_URL_WEBSITE "")
set(demo_URL_BUGTRACKER "")
set(demo_URL_REPOSITORY "")
set(demo_DEPRECATED "")